name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Windows Installer
        run: npm run dist

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Free-Fire-Installer
          path: dist/*.exe
